#!/usr/bin/env python3
"""E4 appendix — circuit resource accounting and fault-tolerant estimate.

Builds the exact ideal circuit of the paper (AngleEmbedding in the X
rotation + StronglyEntanglingLayers + Z readout on wires 0-1) with PennyLane
and reports, per configuration:

  * trainable parameters (VQC weights + classical head);
  * 1q gates (RX embedding + Rot), 2q gates (CNOT), total operations, depth;
  * fault-tolerant estimate: number of synthesised rotation gates and the
    implied T-count under the Ross-Selinger convention
    T_rot(eps) = 3 * log2(1/eps) T gates per arbitrary rotation, with the
    generic-gate lower bound of 3 T gates (Bocharov et al.) as a floor.
    Framed as an estimate with explicit assumptions (reviewer R#2.3).

Grid: qubits {4, 6, 8, 10, 12} x layers {2, 3, 4} for circuit-level counts
(the trained scaling grid is the 5-config subset measured in tab_e234_scaling).
The classical head is reported for the 2-task (4-class) and 5-task (10-class)
variants; quantum resources do not depend on the number of classes.

Outputs:
  analysis/outputs/e4_resources.json
  journal/paper_journal/tables/tab_e4_resources.tex
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "outputs"
TABLES = REPO / "journal" / "paper_journal" / "tables"

import pennylane as qml  # noqa: E402

EPS_SYNTH = 1e-6
T_PER_ROT = 3.0 * math.log2(1.0 / EPS_SYNTH)   # Ross-Selinger convention
T_FLOOR = 3.0                                   # generic 1q gate lower bound


def circuit_specs(n_qubits: int, n_layers: int):
    dev = qml.device("default.qubit", wires=n_qubits)

    @qml.qnode(dev)
    def circuit(x, w):
        qml.AngleEmbedding(x, wires=range(n_qubits))
        qml.StronglyEntanglingLayers(w, wires=range(n_qubits))
        return [qml.expval(qml.PauliZ(i)) for i in (0, 1)]

    x = np.zeros(n_qubits)
    w = np.zeros((n_layers, n_qubits, 3))
    spec = qml.specs(circuit, level="device")(x, w)
    res = spec["resources"]
    gt = {k: int(v) for k, v in dict(res.gate_types).items()}
    # rotation gates: each Rot = 3 Euler rotations; each RX embedding gate = 1
    rot_gates = 3 * gt.get("Rot", 0) + gt.get("RX", 0)
    return {
        "gate_types": gt,
        "num_operations": int(res.num_gates),
        "depth": int(res.depth),
        "rotations_euler": rot_gates,
    }


def rows():
    out = []
    for nq in (4, 6, 8, 10, 12):
        for nl in (2, 3, 4):
            s = circuit_specs(nq, nl)
            vqc = 3 * nq * nl
            fc4 = 2 * 4 + 4      # 2-task: Linear(2 -> 4)
            fc10 = 2 * 10 + 10   # 5-task: Linear(2 -> 10)
            t_est = s["rotations_euler"] * T_PER_ROT
            t_floor = s["rotations_euler"] * T_FLOOR
            out.append({
                "n_qubits": nq, "n_layers": nl,
                "vqc_params": vqc, "fc_4class": fc4, "fc_10class": fc10,
                "rot_1q": s["gate_types"].get("Rot", 0) + s["gate_types"].get("RX", 0),
                "cnot_2q": s["gate_types"].get("CNOT", 0),
                "num_operations": s["num_operations"],
                "depth": s["depth"],
                "rotations_euler": s["rotations_euler"],
                "tcount_floor": t_floor,
                "tcount_est_1e6": t_est,
            })
    return out


def write_table(recs):
    lines = [
        "% Generated by analysis/e4_resources.py -- ideal circuit resources + FT estimate.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\caption{E4 appendix: circuit resources of the trained ansatz "
        "(AngleEmbedding $R_x$ + strongly entangling layers + $Z$ readout on "
        "wires 0--1), noiseless, and a fault-tolerant cost estimate. "
        "\\emph{Params} is the number of trainable rotation parameters of the "
        "VQC; the classical head adds $2k+k$ parameters for $k$ classes. "
        "$T$ is the estimate assuming Ross--Selinger synthesis of each of the "
        "$3n_q n_\\ell + n_q$ Euler rotations at synthesis error "
        "$\\varepsilon=10^{-6}$ ($T_{\\rm rot}\\approx 3\\log_2(1/\\varepsilon)$); "
        "the floor uses the generic single-qubit-gate lower bound of 3 $T$ "
        "gates per rotation (Bocharov et al.). CNOTs are Clifford and "
        "contribute no $T$ gates.}",
        "\\label{tab:e4_resources}",
        "\\begin{tabular}{cccccccc}",
        "\\toprule",
        "$n_q$ & $n_\\ell$ & Params & 1q (Rot+Rx) & 2q (CNOT) & Depth & "
        "$T$ floor & $T$ est.\\ ($\\varepsilon{=}10^{-6}$) \\\\",
        "\\midrule",
    ]
    prev_nq = None
    for r in recs:
        if prev_nq is not None and r["n_qubits"] != prev_nq:
            lines.append("\\midrule")
        prev_nq = r["n_qubits"]
        lines.append(
            f"{r['n_qubits']} & {r['n_layers']} & {r['vqc_params']} & "
            f"{r['rot_1q']} & {r['cnot_2q']} & {r['depth']} & "
            f"{int(round(r['tcount_floor']))} & "
            f"{int(round(r['tcount_est_1e6']))} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (TABLES / "tab_e4_resources.tex").write_text("\n".join(lines))
    print(f"table written: {TABLES / 'tab_e4_resources.tex'}")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    recs = rows()
    payload = {"assumptions": {
        "synthesis": "Ross-Selinger, T_rot(eps) = 3*log2(1/eps)",
        "eps": EPS_SYNTH, "floor": "3 T per generic single-qubit gate",
        "device": "default.qubit, ideal, noiseless",
    }, "records": recs}
    (OUT / "e4_resources.json").write_text(json.dumps(payload, indent=2))
    write_table(recs)
    for r in recs:
        print(f"{r['n_qubits']}q x {r['n_layers']}L: params={r['vqc_params']}, "
              f"1q={r['rot_1q']}, 2q={r['cnot_2q']}, depth={r['depth']}, "
              f"T~{int(round(r['tcount_est_1e6']))} (floor {int(round(r['tcount_floor']))})")


if __name__ == "__main__":
    main()
