#!/usr/bin/env python3
"""Render the E7 (ten-task chains) and E8/E9 (capacity curve) journal tables.

Reads the campaign payloads and writes tables/tab_e7_chains.tex and
tables/tab_e89_capacity.tex with one consistent computation for both.
"""
from __future__ import annotations

import json
import pathlib

import numpy as np
from scipy import stats

BASE = pathlib.Path(__file__).resolve().parent.parent / "hercules_results" / "e234"
OUT = pathlib.Path(__file__).resolve().parent.parent / "journal" / "paper_journal" / "tables"


def load(camp: str, tag: str, arm: str, seeds):
    out = []
    for s in seeds:
        p = BASE / f"e234_{camp}__{tag}__{arm}__ideal__s{s}" / f"results_seed_{s}.json"
        if p.exists():
            j = json.load(open(p))
            m = j["metrics"]["cil"]
            out.append({k: float(m[k]) for k in ("aa", "af")})
    return out


def stats_of(d):
    aa = np.array([x["aa"] for x in d])
    af = np.array([x["af"] for x in d])
    return aa, af


def paired(a, b):
    da = np.array([x["aa"] for x in a])
    db = np.array([x["aa"] for x in b])
    t, p = stats.ttest_rel(da, db)
    return float((da - db).mean()), float(p)


def holm(ps):
    order = np.argsort(ps)
    adj = np.empty(len(ps))
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, (len(ps) - rank) * ps[idx])
        adj[idx] = min(running, 1.0)
    return adj.tolist()


def pf(x):
    return "$<0.001$" if x < 0.001 else f"${x:.3f}$"


# ---------------------------------------------------------------- E7 table
def e7_table():
    rows10 = [("scratch", None), ("synth", "synth"), ("si ($5$)", "si_5"),
              ("er", "er"), ("derpp", "derpp")]
    # (display, key) with keys into the loaded dicts
    sm10 = {
        "scratch": load("smnist10", "std", "scratch", range(10)),
        "synth": load("smnist10", "std", "synth", range(10)),
        "si_0.5": load("smnist10", "si05", "si", range(10)),
        "si_1.5": load("smnist10", "si15", "si", range(10)),
        "si_5": load("smnist10", "std", "si", range(10)),
        "er": load("smnist10", "std", "er", range(10)),
        "derpp": load("smnist10", "std", "derpp", range(10)),
        "ewc": load("smnist10", "std", "ewc", range(10)),
        "ewc1e2": load("smnist10", "ewc1e2", "ewc", range(10)),
    }
    fm10 = {
        "scratch": load("fmnist10", "std", "scratch", range(10)),
        "synth": load("fmnist10", "std", "synth", range(10)),
        "si_5": load("fmnist10", "std", "si", range(10)),
        "er": load("fmnist10", "std", "er", range(10)),
        "derpp": load("fmnist10", "std", "derpp", range(10)),
    }
    order10 = [("scratch", "scratch"), ("synth", "synth"), ("si ($5$)", "si_5"),
               ("er", "er"), ("derpp", "derpp"), ("ewc ($1{\\times}10^4$)", "ewc")]
    orderfm = [("scratch", "scratch"), ("synth", "synth"), ("si ($5$)", "si_5"),
               ("er", "er"), ("derpp", "derpp")]

    def block(groups, order, family=None):
        fam = list(family) if family else [k for _, k in order if k != "scratch"]
        ps = []
        contrasts = {}
        for key in fam:
            d, p = paired(groups[key], groups["scratch"])
            contrasts[key] = (d, p)
            ps.append(p)
        adj = holm(ps)
        holm_map = {k: a for k, a in zip(fam, adj)}
        lines = []
        for disp, key in order:
            aa, af = stats_of(groups[key])
            if key == "scratch":
                diff = "$n/a$ & $n/a$"
            else:
                d, _ = contrasts[key]
                diff = f"${d:+.2f}$ & {pf(holm_map[key])}"
            lines.append(f"{disp} & ${aa.mean():.2f} \\pm {aa.std(ddof=1):.2f}$ & "
                         f"${af.mean():.2f} \\pm {af.std(ddof=1):.2f}$ & {diff} \\\\")
        return lines

    body10 = block(sm10, order10, family=["synth", "si_0.5", "si_1.5", "si_5", "er",
                                          "derpp", "ewc", "ewc1e2"])
    bodyfm = block(fm10, orderfm)
    tex = (
        "% Generated by analysis/render_e79_tables.py from the campaign payloads.\n"
        "\\begin{table}[ht]\n\\centering\n\\small\n\\setlength{\\tabcolsep}{4pt}\n"
        "\\caption{E7: ten-task chains, one class per task, class-incremental, ideal profile, "
        "ten seeds. Average accuracy and average forgetting of the main arms, with the paired "
        "difference of average accuracy against the plain model and its Holm-corrected "
        "probability within each chain. Mean $\\pm$ standard deviation over seeds.}\n"
        "\\label{tab:e7_chains}\n"
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        "Arm & AA & AF & $\\Delta$ vs scratch & $p_{\\text{Holm}}$ \\\\\n\\midrule\n"
        "\\multicolumn{5}{l}{\\textit{split-MNIST, ten tasks ($n=10$)}} \\\\\n"
        + "\n".join(body10) + "\n\\midrule\n"
        "\\multicolumn{5}{l}{\\textit{split-Fashion-MNIST, ten tasks ($n=10$)}} \\\\\n"
        + "\n".join(bodyfm) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_e7_chains.tex").write_text(tex)
    print("[table] tab_e7_chains.tex")


# --------------------------------------------------------------- E89 table
def e89_table():
    conf10 = [("scratch", "std", "q4"), ("scratch", "q6", "q6"), ("scratch", "q8", "q8"),
              ("er", "std", "q4"), ("er", "q6", "q6"), ("er", "q8", "q8"),
              ("derpp", "std", "q4"), ("derpp", "q6", "q6"), ("derpp", "q8", "q8")]
    sm10 = {}
    for arm, tag, col in conf10:
        sm10[(arm, col)] = load("smnist10", tag, arm, range(10))
    sm5 = {}
    for arm, tag, col in [("scratch", "std", "q4"), ("scratch", "q8", "q8"), ("scratch", "q12f", "q12"),
                          ("er", "std", "q4"), ("er", "q8", "q8"), ("er", "q12f", "q12"),
                          ("derpp", "std", "q4"), ("derpp", "q8", "q8"), ("derpp", "q12f", "q12")]:
        sm5[(arm, col)] = load("smnist5", tag, arm, range(5))

    def cell(groups, arm, col):
        aa, _ = stats_of(groups[(arm, col)])
        return f"${aa.mean():.2f} \\pm {aa.std(ddof=1):.2f}$"

    rows10 = []
    for arm in ("scratch", "er", "derpp"):
        rows10.append(f"{arm} & {cell(sm10, arm, 'q4')} & {cell(sm10, arm, 'q6')} & "
                      f"{cell(sm10, arm, 'q8')} & $n/a$ \\\\")
    rows5 = []
    for arm in ("scratch", "er", "derpp"):
        rows5.append(f"{arm} & {cell(sm5, arm, 'q4')} & $n/a$ & "
                     f"{cell(sm5, arm, 'q8')} & {cell(sm5, arm, 'q12')} \\\\")
    tex = (
        "% Generated by analysis/render_e79_tables.py from the campaign payloads.\n"
        "\\begin{table}[ht]\n\\centering\n\\small\n\\setlength{\\tabcolsep}{4pt}\n"
        "\\caption{E8/E9: capacity curve on the class-incremental benchmarks, ideal profile. "
        "Average accuracy (mean $\\pm$ standard deviation) against the number of qubits, equal "
        "to the number of principal components of the encoding. The memory-based arms gain "
        "significantly from four to eight qubits (rehearsal $+5.9$ and dark experience replay "
        "$+4.0$ points on the five-task chain, $+4.8$ and $+2.9$ on the ten-task chain, Holm-"
        "corrected $p \\leq 0.001$), while the plain model does not move, and twelve qubits do "
        "not separate from eight. The ten-task chain uses ten seeds, the five-task chain five "
        "(the twelve-qubit cell, five).}\n"
        "\\label{tab:e89_capacity}\n"
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        "Arm & 4 qubits & 6 qubits & 8 qubits & 12 qubits \\\\\n\\midrule\n"
        "\\multicolumn{5}{l}{\\textit{split-MNIST, ten tasks ($n=10$)}} \\\\\n"
        + "\n".join(rows10) + "\n\\midrule\n"
        "\\multicolumn{5}{l}{\\textit{split-MNIST, five tasks ($n=5$)}} \\\\\n"
        + "\n".join(rows5) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (OUT / "tab_e89_capacity.tex").write_text(tex)
    print("[table] tab_e89_capacity.tex")


if __name__ == "__main__":
    e7_table()
    e89_table()
